In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from numpy.linalg import inv
import tensorflow as tf
import pandas as pd

In [2]:
img1 = mpimg.imread('happyCK.png').flatten()
img2 = mpimg.imread('angerCK.png').flatten()
img3 = mpimg.imread('disgustCK.png').flatten()
img4 = mpimg.imread('fearCK.png').flatten()
img5 = mpimg.imread('neutralCK.png').flatten()
img6 = mpimg.imread('sadCK.png').flatten()
img7 = mpimg.imread('surpriseCK.png').flatten()

data = np.array([img1, img2, img3, img4, img5, img6, img7])
print('x_shape',data.shape)
y = [1,2,3,4,5,6,7]
y_ = tf.constant(pd.get_dummies(y).values.astype(np.float32))
print('y_data',y_)

x_shape (7, 2304)
y_data tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]], shape=(7, 7), dtype=float32)


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, input_shape=(data.shape[1],), activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(128, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(32, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(48, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(7, activation=tf.keras.activations.softmax)
])

model.compile(optimizer='adam', loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

history = model.fit(data, y_, epochs=500, batch_size=8, validation_split=0.2)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 1.9858 - accuracy: 0.2000 - val_loss: 2.0277 - val_accuracy: 0.0000e+00
Epoch 2/500
1/1 [==============================] - 0s 48ms/step - loss: 1.8904 - accuracy: 0.2000 - val_loss: 2.3367 - val_accuracy: 0.0000e+00
Epoch 3/500
1/1 [==============================] - 0s 60ms/step - loss: 1.7343 - accuracy: 0.4000 - val_loss: 2.5655 - val_accuracy: 0.0000e+00
Epoch 4/500
1/1 [==============================] - 0s 51ms/step - loss: 1.6887 - accuracy: 0.2000 - val_loss: 2.7928 - val_accuracy: 0.0000e+00
Epoch 5/500
1/1 [==============================] - 0s 52ms/step - loss: 1.6076 - accuracy: 0.2000 - val_loss: 3.0354 - val_accuracy: 0.0000e+00
Epoch 6/500
1/1 [==============================] - 0s 44ms/step - loss: 1.5123 - accuracy: 0.4000 - val_loss: 3.2035 - val_accuracy: 0.0000e+00
Epoch 7/500
1/1 [==============================] - 0s 42ms/step - loss: 1.4191 - accuracy: 0.4000 - val_loss: 3.3402 - val_accuracy: 0.000

In [4]:
img7 = img7.reshape(1, -1)
print(img7.shape)
model.predict(img7)

(1, 2304)
1/1 [==============================] - 0s 119ms/step


array([[1.0605540e-01, 3.5169548e-01, 1.7514719e-01, 1.2768770e-02,
        3.5431430e-01, 6.9785515e-06, 1.1829848e-05]], dtype=float32)

In [5]:
img6 = img6.reshape(1, -1)
print(img6.shape)
model.predict(img6)

(1, 2304)
1/1 [==============================] - 0s 23ms/step


array([[5.8999908e-01, 1.7403211e-06, 9.2117663e-04, 3.8917032e-01,
        1.9899346e-02, 7.6999368e-06, 6.0117850e-07]], dtype=float32)

In [6]:
img5 = img5.reshape(1, -1)
print(img5.shape)
model.predict(img5)

(1, 2304)
1/1 [==============================] - 0s 23ms/step


array([[1.4041555e-05, 4.5942768e-05, 1.2228309e-05, 9.3930785e-06,
        9.9991822e-01, 1.4362064e-08, 8.0263000e-08]], dtype=float32)

In [7]:
img4 = img4.reshape(1, -1)
print(img4.shape)
model.predict(img4)

(1, 2304)
1/1 [==============================] - 0s 30ms/step


array([[2.67676751e-06, 8.08357179e-13, 3.12845732e-05, 9.99966145e-01,
        4.02173903e-08, 1.49337660e-11, 1.13376156e-10]], dtype=float32)

In [8]:
img3 = img3.reshape(1, -1)
print(img3.shape)
model.predict(img3)

(1, 2304)
1/1 [==============================] - 0s 35ms/step


array([[1.4763129e-06, 7.7906712e-05, 9.9988997e-01, 2.7822744e-05,
        2.7968701e-06, 7.8179477e-11, 1.1827850e-08]], dtype=float32)

In [9]:
img2 = img2.reshape(1, -1)
print(img2.shape)
model.predict(img2)

(1, 2304)
1/1 [==============================] - 0s 30ms/step


array([[2.4265428e-06, 9.9987006e-01, 7.1217597e-05, 2.6079196e-08,
        5.6259480e-05, 1.0362425e-10, 1.2557759e-09]], dtype=float32)

In [10]:
img1 = img1.reshape(1, -1)
print(img1.shape)
model.predict(img1)

(1, 2304)
1/1 [==============================] - 0s 29ms/step


array([[9.9998522e-01, 3.4322716e-06, 2.7160527e-07, 4.7409048e-06,
        6.1035739e-06, 1.7333373e-07, 4.4512359e-11]], dtype=float32)